services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx-https.conf:/tmp/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./ssl/server.crt:/etc/ssl/certs/server.crt
      - ./ssl/server.key:/etc/ssl/private/server.key
      - ./ssl/server.pem:/etc/nginx/dhparam.pem
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
    container_name: flask
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src